project:
  type: website
  output-dir: docs
  resources:
    - googlef0fd5969082931d4.html

website:
  title: "小學生筆記"
  favicon: "images/icon.jpeg"
  site-url: "http://cccc0423.github.io/"
  navbar:
    right:
      - href: about.qmd
        text: 關於
  page-footer:
    left: ""
    center: "This site is powered by [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/
      - icon: facebook
        href: https://www.facebook.com/

format:
  html:
    theme:
      - zephyr
      - custom.scss
    css: styles.css
    toc: true

