---
title: "週記（十一）"
subtitle: "天地玄黃，宇宙洪荒"
date: 2025-04-05
categories: [ "週記" ]
include-after-body: "../emphasis-point.html"
margin-header: |
  >  <ruby>
  >    週<rt>ㄓㄡ</rt>記<rt>ㄐㄧˋ</rt>
  >  </ruby>
  >  <br>
  >  <div style="font-size: 0.8em">當週隨手寫下的流水帳。</div>
---

## 修課

書法課沒有上新的東西，因為下週要考試，因此這週稱為考前複習。

統計學習課這週在教 model selection。老師不到三堂課就把 ESL 的第 7 章上完了。讀到現在我真不覺得 ESL 是一本適合入門統計學習或機器學習的書。有空的話或許應該也要去讀 Pattern Recognition and Machine Learning（PRML），這本書感覺更容易上手。說到 model selection，這個經濟系在計量課多少會教到一點點。不過我覺得大多數人的理解都很片面。改天來寫一篇短文介紹這邊的 big picture。

## 研究與閱讀

這週只讀了一篇文章。

### Artmann, Oosterbeek, and van der Klaauw (2022)

這篇文章發在 AEJ: Applied，標題是 Do Doctors Improve the Health Care of Their Parents? Evidence from Admission Lotteries。作者研究子女成為醫生是否會改善父母的健康照護和降低死亡率。

民眾的醫療照護使用可能因為與健康無關的因素而存在差異，例如沒有充分的健康資訊、難以與醫療照護者溝通或者醫療照護的提供者可能差別對待不同背景的患者。作者注意到近期有一批文獻，透過比較醫生與其親屬與對照組，來研究以上這些原因的綜合影響。問題在於，醫生與其親屬這群人很可能與其他人很不一樣，以致我們不應該拿這群人與普羅大眾相比。那要如何研究健康資訊與近用對於健康照護的影響呢？

荷蘭的大學原則上允許所有中學畢業生入學。然而，由於在 1960 年代末期，醫學院申請人數急劇增加，超過可用名額，因此引入了配額制度。在 1999 年之前，申請醫學院的學生需要參加抽籤，決定哪些學生可以進入醫學院，然後再將這些學生分配到荷蘭的八所醫學院。抽籤的權重依據學生中學畢業考試的 GPA 決定，學生會根據其 GPA 被劃分為不同的類別，每個類別在抽籤中擁有不同的權重。

作者於是利用抽籤結果作為自然實驗，以申請醫學院的學生在第一次抽籤中獲得入學名額的機會作為工具變數，來研究子女成為醫生對父母健康照護的影響。本文的 structural equation 如下：
$$
Y_{it} = \alpha_t + \delta D_i + X_{i} \beta + \mathit{LC}_{i} + U_{it},
$$
其中 $Y_{it}$ 是子女 $i$ 的父母在時間 $t$ 的結果變數，$D_i$ 是子女 $i$ 是否成為醫生的變數，而 $\delta$ 是作者感興趣的變數，$X_{i}$ 是數個控制變數與固定效果，$\mathit{LC}_{i}$ 是子女 $i$ 彩券類別和首次參與年份之間的交乘項（中籤機率完全取決於類別與參與年份），$\alpha_t$ 是時間固定效果。

作者發現子女成為醫師對父母死亡率的因果效應接近於零，且統計上不顯著；對於其父母多數的醫療照護利用變數的影響在統計上也不顯著。作者認為至少在荷蘭的情境中，透過身為醫生的子女而獲得醫療專業知識和服務，並非造成父母醫療照護利用和死亡率差異的重要原因。

這篇文章在計量上沒什麼創舉（通常那些說自己使用 novel identification strategy 但沒有給出嚴謹的論證的東西感覺比較值得多想想），不過作者在 hazard rate 的分析只有跑 reduced-form 模型，他在腳注裡說工具變數法不太容易與非線性的 hazard rate 模型結合。我感覺（雖然還未仔細研究過）這種情況下可以用 control function 的方法來處理。簡單來說，就是把 first stage residuals 加進 second stage 的模型裡，以當作 unobserved confounders 的代理變數。我後來查了一下在存活分析中確實有這樣一招，就稱為 two-stage residual inclusion (2SRI)。


## 其他

這學期當 KM 的大二計量課助教。這學期的計量課用 Bruce Hansen 的課本（我也是看這本課本才真正入門計量的，因此我有買這本書！）。通常 Hansen 的課本會當作經濟系碩博班必修課的用書。所以這本書確實對大多數的大二學生來說比較難上手。為了讓學生知難而退，KM 在課程大綱中就提及這門課一週大約要花 20 小時，還考了期初考（平均 50 分）。可是不僅實體課堂的出席率不高，課程影片也沒什麼人在看，並除了 lab 的學生以外，很少人去他或助教的 office hour。因此，他上週發了一封信，名為 Volker shock，裡面講到 Fed 主席 Volker 在 1980 年代的時候，為了對抗通貨膨脹，將利率提高到 20%。這樣的做法造成很大的衝擊，但也讓通貨膨脹回落。KM 說必要的話他也會這樣做。

結果這封信引起軒然大波，有一篇相關的討論文章，甚至一度成為 Dcard 臺大板的熱門文章。文章的作者覺得自己絕對不是不用功的學生，但是老師的教學品質非常差。當然留言區就是正反意見都有。後來 KM 也找我們簡單地開了個會。他說他心目中的模範就是他當年修的陳金次的高等微積分。這門課的負擔他估計大約是當時那門高微的 70%。他並堅持不會修改教學目標和要求。因為他希望這對來年的學生是個有效地訊號。那些想要一週花 20 小時學 Hansen 的才會來他的班。我覺得挺有趣的。不知道我會不會有機會當老師，也不知道屆時應該如何教學生、要求學生。

---

努力想想除了工作、讀書和耍廢的時候在做些什麼。

週一在住處自己煮了一些蔬菜和雞胸肉。最近覺得因為外食，自己真是吃太少蔬菜了。因此偶爾開始煮一些方便的蔬菜。

週三和大學同學在忠孝復興站附近吃了烤魚、喝了雞湯，都還不錯。雞湯很適合獨食，是如果在附近不知道要吃什麼，會想去吃的餐廳。

週四第一次去了遠企樓下的 city'Super，店內空間不大，但有很多舶來品。有空的話應該仔細逛逛。拿到了 F 的草莓蛋糕，好吃。

週五去了好久沒去的未央。上次去可能是大四吧，熬夜準備線性代數的期考（結果考很爛😭）。蜂蜜柚子茶有點太甜。莓果蛋白餅好吃，但餅乾本人有點像是比較脆的旺仔小饅頭。

週六練了一晚上的書法。