---
title: "週記（四）"
subtitle: "開學前一週"
date: 2025-02-15
categories: [ "週記" ]
include-after-body: "../emphasis-point.html"
margin-header: |
  >  <ruby>
  >    週<rt>ㄓㄡ</rt>記<rt>ㄐㄧˋ</rt>
  >  </ruby>
  >  <br>
  >  <div style="font-size: 0.8em">當週隨手寫下的流水帳。</div>
---

這週暈頭轉向，不知道自己在做什麼。每天都睡不好，早上起床時總是覺得沒有休息足夠。根據 Apple Watch 顯示，一晚可以醒來十多次。又或者，我會做一些很複雜的夢。週二晚上至週三的夢境有被我簡單記錄下來。

我在夢裡也在做夢。夢中的夢經過各地——那些在我潛意識中重要的地方——旅行。最後在一家餐廳用餐。一個以前的學長與他的家人也在那裡。奇怪的是他裸著上身用餐。我在夢裡看到這個人，不禁感懷與這個人相處的過程，想到大概很久以後才會再見了，當下還百感交集碩二上正式結束了。

然後我從夢中夢醒來。到了白天，不知為何我開始練習滑板，然後我和另一位高中同學交談。或許這也是我比較懷念的人。我們交談直到我意識到我在做夢。

---

最近幾週心情都莫名其妙地悲痛，也常常想起一些難以理解的回憶。

我想到一個以前認識的人。快兩年前，他斷崖式地消失了，還封鎖我的 Instagram 和 Twitter，刪除了我的臉書。^[直到最近幾個月，他又解封了我的 Twitter 然後重新追蹤我，但我們沒有任何互動。] 不知道對方如何看待我。不過直到現在我還是認為對方有很多優點。難以理解他為何這樣對待我——儘管我也知道我有很多缺點，但也不至於此吧！我感覺這件事情帶給我不小的創傷。而我因此情緒低落好久。

直到現在，有些人際互動中的小小片段還是讓我想起這份難堪的回憶。我只能慶幸自己還能覺得受傷，而不至於麻木不仁，因為這是我曾經真誠付出感情的證明。

但是，要怎麼超越這份悲痛？不知道，希望我還能成長，變成更好的人。

---

我報名了今年 5 月的 GRE 考試。這意味著應該要好好開始準備了。先從背 Magoosh 的單字開始吧。

---

週四下雨。我想測試看看怎麼去衛福部比較快，於是我計劃從住處騎腳踏車到忠孝敦化，然後再搭捷運到昆陽。當天下雨，結果我在仁愛圓環摔倒。路人紛紛轉頭看我。有點糗，不過我快速地起身，確認只有一點小挫傷後，趕緊騎腳踏車離開。但好像有點頭暈了，竟然在仁愛路上迷路，繞了一下才確定方向。

從衛福部離開以後，我搭捷運到市府轉運站的傘店送修早上因為摔倒而弄壞的雨傘。送修要等一個月，所以我想著再買一把傘備用。店裡阿姨一直推薦我買一把很樸實機能性很好的傘，但我一直覺得外觀不太好看。最後我買了一把有趣的花花雨傘。晚上晾衣服，晾衣服，看到去日本旅遊買的 Snoopy 帽 T，覺得應該多買一點有趣的衣服才對。這時我突然想通為什麼自己想買有趣的傘：因為我本人太無聊了，應該要多買一些有趣的東西😔。

晚餐在時代百貨裡吃大戶屋。鄰座是一對母子。男生感覺年紀比我大一兩歲，他和他的媽媽邊吃飯邊聊天。我很羨慕他和他媽媽的互動。他媽媽和他說最近自己去了昆明旅遊，還和他抱怨最近公司人事調度。只聽聲音可能還會以為是朋友間的談話。

---

我從小就沒怎麼經歷社會化。我爸媽很少出門，也很少帶我出門、讓我出門。所以我大部分的人際關係都很扁平。也因此我相對於別人一直都不那麼理解社會規範。這有好有壞，畢竟所謂社會規範同樣是有好有壞。

以戀愛關係而言，因為小時候幾乎沒有看過影劇漫畫，我爸媽也不太展現那些典型的互動模式（雖然我爸媽並不是很好的範本）。不過在我心中，一切就是很樸素的兩個人喜歡彼此、對彼此好。我真的很晚才學習到那套主流的異性戀的戀愛腳本（比如男生要怎麼寵女生，女生要如何暗示男生等等）。隨著年紀越來越大越討厭這套腳本。可惜我讀的書不夠多，有口難言，很難說清楚為何我不喜歡這套腳本。一開始可能是因為覺得俗氣，後來慢慢覺得背後有更多問題。在此從略。不過我就是不明白，為什麽不能只是因為感受到對方的心意而開心？

不太理解社會規範這件事還可以應用到很多其他場合。似乎我就是非常我行我素，只要我覺得是對的，重要的事情，就不想退讓。改天想到再寫。

---

週五下午又參加 EMI TA 培訓。

因為擔心另外兩位計量導的 TA 都沒有參與 EMI TA 培訓，到時候報帳或 TA 資格會比較麻煩，因此我去年就參加過一次 EMI TA 培訓。但後來顯然是多慮了，KM 其實沒有成功申請到 EMI 的補助，所以我雖然全程參加，但最後想著「我以後應該不會需要擔任 EMI TA 吧」，就沒有繳交某些文件。

結果今年換我要當計量導的 EMI TA。週五下午又花了兩個小時參加培訓，幾乎所有環節都與去年一樣。這種場合真的是什麼人都有。第一小時，與我同桌的一個男生（亞洲人，但英語口音並不是中文或者常見的英語系國家口音）一直吃東西，徒手抓著麵包，手指沾了奶油。他比手畫腳之間，還把麵包屑撥到他旁邊男生身上。第二小時，我參與設計活動的場次。我們要設計一個課堂活動，讓學生預習或複習全球暖化的知識。同組有個讀醫學工程的女生，英文講得很好，口音也很標準美式，但感覺大家都聽不太懂他在說什麼。就這樣度過了兩個小時。
