---
title: "週記（五）"
subtitle: "開學第一週"
date: 2025-02-15
categories: [ "週記" ]
include-after-body: "../emphasis-point.html"
margin-header: |
  >  <ruby>
  >    週<rt>ㄓㄡ</rt>記<rt>ㄐㄧˋ</rt>
  >  </ruby>
  >  <br>
  >  <div style="font-size: 0.8em">當週隨手寫下的流水帳。</div>
---

這是我在臺大第十二個學期。

## 開學

### 書法課

從來沒有跨校選課，這是第一次，選了一門師大的書法課。

週一下午兩點四十五分，我在住處附近買了一杯可不可，沿著和平東路，騎 YouBike 到師大。我想提前一些，避免找不到教室。這樣的擔心果然不是多餘的，我找了好一陣子，才找到教室。在抵達教室之前，我先去了和平 II 校區，後來才發現原來教室是在和平 I 校區。

然後我穿過行政大樓——建築風格與臺大的相似——到了文學院。文學院給人一種擁擠的感覺。下課時間，幾乎每間教室門口都有人在等待。

不過我也想到或許其實如駱明慶所說，是臺大社科院的教室太空。坐定位以後，我還是感覺蠻緊張的。我感覺自己像是重溫剛上大學的那種忐忑不安心情。希望能從這門課中學到一些東西。

### 週四晚餐

KM 覺得我可能對計量感興趣，上週便問我要不要和 JR 吃晚餐，時間是週四晚上。我答應了。不過，上週五 YC 打球受傷，因此 KM 說改在 YC 家吃晚餐。

聽完 JR 的 CRETA seminar 以後，我們搭捷運到古亭站，然後 YC 的太太領我們到 YC 家。這時，YC 的爸媽正在準備晚餐。我一直都很不適應社交場合，這時候顯得更尷尬，只能尷尬地笑。

YC 的媽媽廚藝不錯。不過也因為是 YC 的媽媽煮飯，我不好意思挑食，連番茄湯裡的洋蔥都吃了。

飯桌上大家都是有一搭沒一搭的開一些隨機的話題。畢竟平常也不是多常見面的人，有點考驗社交的能力（我完全沒有）。我記得上次跟 Alice 聊天後，KM 問我聊得如何，我說我常常不知道要跟他說什麼，有點尷尬。他說，聊天也是需要多練習的。大概是這樣吧。

YC 的家庭應該不算是非常有錢，但生活還算是過得不錯。他們是外省人。據說，他媽媽的家庭到臺灣以前應該過得蠻舒適的，不過來臺灣就是什麼都沒帶，聽說在他媽媽出生前，長輩也把傭人都遣散了。有趣的是，他爸還說他媽媽的祖父（也就是 YC 的外曾祖父）臨終前還告訴兒女，「遲早要回大陸去的！」（當時兩岸還沒有交流）。

此外，也就是隨機地見過幾次面，意想不到的是 YC 的爸媽對我這張臉還有印象。


### 其他課程

除了書法課，我還聽了一堂「統計管制與最佳化方法概論」。這門課對我來說太簡單了，因此我只是坐在教室裡頭，沒打算要選這門課。我猜這門課適合工學院，特別是工業工程領域，而對應用統計感興趣的人。

我也去上統計所開的「統計學習」，老師教 *Elements of Statistical Learning*。沒意外的話我會修這門課。這門課似乎不是被定位成一門理論課，畢竟 ESL 的內容真的包山包海，要想教得深入真的很難。第一週老師就帶過了第一、二章，跳過第三章以後，開始講第四章。乍聽之下他講得蠻清楚的。只是 ESL 可以練習的東西真的很多，比如學習重製課本圖表之類的，感覺就要花不少時間。希望能拿捏好時間。

## 研究與閱讀

這週去了一天半的衛福部：週三早上、週四早上、週五下午。開學以後的時間不得不分配得更緊湊、更零碎。沒什麼研究上的進展，也沒有讀書。要趕緊找到碩論題目，調整好步調，然後恢復閱讀。

## 其他

記錄一下新吃了什麼。

週一吃了溫州街蘿蔔絲餅達人。這間似乎是名店，週一傍晚路過看到大排長龍，於是跟著排隊。我第一次吃蘿蔔絲餅，就是油炸的麵團包著蘿蔔絲。味道還可以，裡頭的蘿蔔絲很多，吃起來有點脆脆的，不過網路上也有人說他們不喜歡這樣偏生的口感。我倒是覺得還好。我還點了蔥油餅，同樣是油炸的。我比較喜歡蔥油餅。不知道是不是因為我放冷了才吃，感覺非常油，但蔥香味道還不錯。以價格和味道而言還不錯，是如果不用排太久的隊，而且吃垃圾食物的額度還沒用罄的時候會想吃的店。

週六吃了 Boulangerie Ours，四維路上的歐式麵包店。我買了一根長棍、一個肉桂捲（sticky bun）、一個蘆筍培根佛卡夏和一塊巧克力餅乾。都很好吃。長棍外皮酥脆，內裡軟綿，味道不錯。肉桂捲的肉桂、堅果和焦糖味都很香。佛卡夏的蘆筍很鮮嫩，培根的鹹味和起司的香氣很搭。巧克力餅乾的巧克力味道很濃。下次還會再訪，試試看酸種和三明治。